# Resolução da Lista de Exercícios 2

In [4]:
### TADS 
class Stack :
    # Cria uma pilha vazia.
    def __init__( self ) :
        self._topo = None
        self._tam = 0

    # Retorna verdadeiro se a pilha esta vazia ou false caso contrário.
    def estaVazia( self ) :
        return self._topo is None

    # Retorna o número de elementos na pilha.
    def __len__( self ) :
        return self._tam

    # Retorna o elemento no topo da pilha sem removê-lo.
    def peek( self ) :
        assert not self.estaVazia(), "Não pode acessar o topo de uma pilha vazia"
        return self._topo.elem

    # Remove e retorna o elemento no topo da pilha.
    def pop( self ) :
        assert not self.estaVazia(), "Não pode remover de uma pilha vazia"
        no = self._topo
        self._topo = self._topo.prox
        self._tam -= 1
        return no.elem

    # Insere o item no topo da pilha.
    def push( self, elem ) :
        self._topo = _NoPilha( elem, self._topo)
        self._tam += 1

class _NoPilha :
    def __init__( self, elem, link ) :
        self.elem = elem
        self.prox = link

# Livro: Data Structures and Algorithms Using Python. Rance Necaise. 2011.
# listaEncadeadaOrdenada.py - 
# Implementa um TAD Lista ordenada usando uma lista encadeada.
# Neste tipo de lista os elementos são inseridos na ordem certa.

#implementa uma TAD Lista ordenada usando uma lista encadeada

# classe para a lista ordenada usando lista encadeada
class ListaOrd:
    # Constroi uma lista vazia
    def __init__(self):
        self._head = None # Referencia ao primeiro elemento
        self._tamanho = 0 # Número de elementos

    # Retorna o numero de elementos na lista. 
    def __len__(self):
        return self._tamanho

    # Determina se um elemento se encontra na lista.
    def __contains__(self, elem):
        noAtual = self._head
        while noAtual is not None and noAtual.elem < elem :
            noAtual = noAtual.next
        if noAtual.elem == elem :
           return True                # Retorna true se encontrou o elemento
        else :
           return False 
          
    # Adiciona um novo elemento na lista ordenada.
    def adiciona(self, elem):
        predNo = None
        noAtual = self._head
        while noAtual is not None and elem > noAtual.elem :
            predNo = noAtual
            noAtual = noAtual.next

        novoNo = _noLista(elem)    # Cria um novo nó, objeto _noLista()
        novoNo.next = noAtual      # Encadeia o novoNo antes do noAtual    

        if noAtual == self._head :
           self._head = novoNo     # Encadeia o novo elemento na frente
        else :
           predNo.next = novoNo    # Encadeia o novoNo após o predNo 
        self._tamanho += 1         # Incrementa o numero de elementos

    # Remove o elemento elem na lista ordenada.
    def remove(self, elem):
        predNo = None              # No predecessor
        noAtual = self._head       # No atual
        while noAtual is not None and noAtual.elem < elem:
            predNo = noAtual
            noAtual = noAtual.next

        assert noAtual is not None, "O elemento deve estar na lista!"
        self._tamanho -= 1
        if noAtual is self._head:       # Elemento está na primeira posição
            self._head = noAtual.next   # Realiza o encadeamento para exclusão
        else:
            predNo.next = noAtual.next  # Realiza o encadeamento para exclusão
        return noAtual.elem

    # Cria um iterador para percorrer a lista. 
    def __iter__(self):
        return _IteradorListaNOrd(self._head) # Objeto iterador

# classe para criar um nó da lista encadeada
class _noLista(object):
    # construtor do objeto 
    def __init__(self, elem):
        self.elem = elem    # elemento armazenado
        self.next = None    # referencia ao proximo objeto

# clase para o iterador da lista
class _IteradorListaNOrd:

    # Cria o iterador com uma referencia ao no atual
    def __init__(self, listHead):
        self._noAtual = listHead

    # Retorna uma referencia ao iterador
    def __iter__(self):
        return self

    # Retorna o elemento atual da lista e posiciona no próximo
    def __next__(self):
        if self._noAtual is None:
            raise StopIteration
        else:
            elem = self._noAtual.elem
            self._noAtual = self._noAtual.next
            return elem




### 1. Escreva um programa que converta um número decimal em hexadecimal, usando o método de divisões sucessivas e uma pilha. Obs. Lembrar que caso o resto da divisão for 10, 11, 12, 13, 14 ou 15, o digito correspondente deverá ser A, B, C, D, E ou F.

In [3]:
def Hexa(decimal):
    hexa = Stack()
    resultado = []
    dicionario = {10:"A",11:"B",12:"C",13:"D",14:"E",15:"F"}
    while decimal > 0:
        hexa.push(decimal % 16)
        decimal = decimal // 16
    while not hexa.estaVazia():
        resultado.append(hexa.pop())
    print(''.join(map(str,[dicionario.get(x,x) for x in resultado])))
      
Hexa(511)

1FF


### 2. Um palíndromo é uma string que pode ser lida para frente e para trás com o mesmo resultado. Por exemplo, as seguintes frases são palíndromos:

    A base do teto desaba.
    
    A diva em Argel alegra-me a vida.
    
    Adias a data da saída.
    
    Socorram-me, subi no ônibus em Marrocos.
    
Observe que nos palíndromos se deve ignorar o espaçamento, a pontuação, e as diferenças entre letras maiúsculas e minúsculas.
Escreva uma função para testar se uma string é um palíndromo usando uma pilha. A ideia é armazenar os caracteres da string na pilha e recuperar eles formando uma nova string. Depois comparar a nova string com a string original. Teste a sua função com os exemplos mostrados acima.

In [81]:
#Precisamos de uma função pra normalizar os acentos, pontuação e maiúsculas
import re
def Normaliza(s):
    return ''.join(c for c in unicodedata.normalize('NFD', re.sub(r'[^\w\s]','',s).lower().replace(' ',''))
                  if unicodedata.category(c) != 'Mn')

def Testa_Palindromo(frase_raw):
    frase = Normaliza(frase_raw)
    stack_frase = Stack()
    for letra in frase:
        stack_frase.push(letra)
    for i in range(len(frase)):
        if stack_frase.pop() != frase[i]:
            return False
    return True

list(map(lambda s:Testa_Palindromo(s),["A base do teto desaba.",
                                  "A diva em Argel alegra-me a vida.",
                                  "Adias a data da saída.",
                                  "Socorram-me, subi no ônibus em Marrocos."
                                  "Navegar é preciso."]))      
        

[True, True, True, False]

### 3. Modifique o programa de casamento de parênteses para considerar o casamento de { }, [ ] e ( ). O programa deverá verificar a correspondência entre o símbolo de abertura e seu correspondente de fechamento.  Identifique e reporte os tipos de erro possíveis caso existam, indicando a linha, ou uma mensagem indicando que o casamento é perfeito. Teste o seu programa com arquivos de texto, com erros e sem erros.   

In [8]:
#texto = "()))  \n[]{{}"
texto = "([{}) \n ([{]) \n ([{}]"
def Abrir(arquivo_texto):
    with open(arquivo_texto,encoding="ISO-8859-1") as f:
        lines = f.readlines()
    return ''.join(lines)
texto2 = Abrir("texto1.txt")

def Casamento(texto):
    texto_linhas = texto.split("\n")
    parenteses = Stack()
    chaves = Stack()
    colchetes = Stack() 
    stacks = {
        "(":parenteses,
        "[":colchetes,
        "{":colchetes
    }
    conversor = {
        ")":"(",
        "]":"[",
        "}":"{"   
    }
    
    for i in range(len(texto_linhas)):
        for caractere in texto_linhas[i]:
            if caractere in ["(","[","{"]:
                stacks[caractere].push(caractere)
            if caractere in [")","]","}"]:
                try:
                    stacks[conversor.get(caractere)].pop()
                    print(conversor[caractere],caractere,"Casamento perfeito na linha",(i+1))
                except AssertionError:
                    print("ERRO de tentar fechar",caractere,"a mais na linha",(i+1))
                       
        if not parenteses.estaVazia():
            print("ERRO de",parenteses.__len__(),"( abertos na linha", (i+1))
            parentesesses = Stack()
        if not colchetes.estaVazia():
            print("ERRO de",colchetes.__len__(),"[ abertos na linha", (i+1))
            colchetes = Stack()
        if not chaves.estaVazia():
            print("ERRO de",chaves.__len__(),"{ abertos na linha", (i+1))
            chaves = Stack()
        
                                  
Casamento(texto)

{ } Casamento perfeito na linha 1
( ) Casamento perfeito na linha 1
ERRO de 1 [ abertos na linha 1
[ ] Casamento perfeito na linha 2
( ) Casamento perfeito na linha 2
{ } Casamento perfeito na linha 3
[ ] Casamento perfeito na linha 3
ERRO de 1 ( abertos na linha 3


### 8 - Escreva um programa que some polinômios. Cada polinômio deve ser representado como uma lista encadeada. O primeiro nó na lista representa o termo de maior grau, enquanto que o último representa o termo de menor grau. Cada nó contém três campos: 
i) coeficiente do termo;
ii) expoente do termo; 
iii) o ponteiro ao seguinte termo.

Os polinômios podem ser adicionados utilizando um processo de intercalação. As duas listas são combinadas por intercalação, além de realizar uma operação de soma quando os exponentes forem iguais.  Observe o exemplo da Figura.
Regras para a adição:


1. Se os expoentes são iguais, os coeficientes são somados e o resultado inserido;

2. Se os expoentes são diferentes, o termo com maior expoente devera ser inserido, enquanto o menor aguarda para ser comparado com outro termo. 

3. Se o resultado da adição é 0, o termo deve ser eliminado do polinômio soma.

4. Se um polinômio termina antes o outro, os termos restantes do polinômio maior serão adicionados no polinômio soma.

Os dados do polinômio (coeficientes e potências) podem ser lidos de um arquivo ou ingressados do teclado. Imprima os dois polinômios de entrada e o polinômio soma.



In [153]:
#Modificando o tad?

# classe para a lista ordenada usando lista encadeada
class Poli:
    # Constroi uma lista vazia
    def __init__(self):
        self._head = None # Referencia ao primeiro elemento
        self._tamanho = 0 # Número de elementos

    # Retorna o numero de elementos na lista. 
    def __len__(self):
        return self._tamanho

    # Determina se um elemento se encontra na lista.
    def __contains__(self, elem):
        noAtual = self._head
        while noAtual is not None and noAtual.elem < elem :
            noAtual = noAtual.next
        if noAtual.elem == elem :
           return True                # Retorna true se encontrou o elemento
        else :
           return False 
          
    # Adiciona um novo elemento na lista ordenada.
    def adiciona(self, elem): 
        predNo = None
        noAtual = self._head
        while noAtual is not None: #tirei a ccondição do no atual ser menor que o anterior, mas talvez pudesse modificar de modo a automaticamente organizar os nós pelo expoente. E talvez aqui já possibilitar a soma de polinomios
            predNo = noAtual
            noAtual = noAtual.next

        novoNo = _noLista(elem)    # Cria um novo nó, objeto _noLista()
        novoNo.next = noAtual      # Encadeia o novoNo antes do noAtual    

        if noAtual == self._head :
           self._head = novoNo     # Encadeia o novo elemento na frente
        else :
           predNo.next = novoNo    # Encadeia o novoNo após o predNo 
        self._tamanho += 1         # Incrementa o numero de elementos

    # Remove o elemento elem na lista ordenada.
    def remove(self, elem):
        predNo = None              # No predecessor
        noAtual = self._head       # No atual
        while noAtual is not None and noAtual.elem < elem: 
            predNo = noAtual
            noAtual = noAtual.next

        assert noAtual is not None, "O elemento deve estar na lista!"
        self._tamanho -= 1
        if noAtual is self._head:       # Elemento está na primeira posição
            self._head = noAtual.next   # Realiza o encadeamento para exclusão
        else:
            predNo.next = noAtual.next  # Realiza o encadeamento para exclusão
        return noAtual.elem

    # Cria um iterador para percorrer a lista. 
    def __iter__(self):
        return _IteradorListaNOrd(self._head) # Objeto iterador


    def PrintPoli(self):
        mais = False
        for element in self:
            if mais:
                print(' + ',end='') #ainda não vi uma forma de não imprimir o último +
            mais = True
            if element[0] == 0:
                pass
                mais = False
            else:
                print(str(element[0]),end='')
                if element[1] == 0:
                    pass
                else:
                    if element[1] == 1:
                        print('x',end='')
                    else:
                        print("x^{}".format(element[1]),end='')
        print()

# classe para criar um nó da lista encadeada
class _noLista(object):
    # construtor do objeto 
    def __init__(self, elem):
        self.elem = elem    # elemento armazenado
        self.next = None    # referencia ao proximo objeto
        self.coeficiente = elem[0]
        self.expoente = elem[1]

# clase para o iterador da lista
class _IteradorListaNOrd:

    # Cria o iterador com uma referencia ao no atual
    def __init__(self, listHead):
        self._noAtual = listHead

    # Retorna uma referencia ao iterador
    def __iter__(self):
        return self

    # Retorna o elemento atual da lista e posiciona no próximo
    def __next__(self):
        if self._noAtual is None:
            raise StopIteration
        else:
            elem = self._noAtual.elem
            self._noAtual = self._noAtual.next
            return elem






def LerPoli(poli_str):
    poli_list = poli_str.replace(' ','').replace('-','+-').split("+")

    poli_final = Poli()
    poli = []
    for element in poli_list:
        if(element.__contains__("x^")):
            coeficiente, expoente = element.split("x^")
            poli.append([int(coeficiente),int(expoente)])
        elif(element.__contains__("x")):
            coeficiente, expoente = element.split("x")
            poli.append([int(coeficiente),1])
        else:
            poli.append([int(element),0])
    poli = sorted( poli, key=lambda x: int(x[1]) ,reverse=True)

    for elemento in poli:
        #print(elemento)
        poli_final.adiciona(elemento)
    return poli_final


def SomaPoli(poli_1, poli_2):
    polinomio = Poli()
    poli_1_list = []
    poli_2_list = []
    poli_resultado = []
    for element in poli_1:
        poli_1_list.append(element)
    for element in poli_2:
        poli_2_list.append(element)
    poli_resultado = poli_1_list + poli_2_list
    expoentes = set([x[1] for x in poli_resultado])
    poli_resultado = [ [sum(poli[0] for poli in poli_resultado if poli[1] == expoente),expoente] for expoente in expoentes]
    poli_resultado = sorted(poli_resultado, key=lambda x: int(x[1]) ,reverse=True)

    
   # print(poli_resultado)
    for poli in poli_resultado:
        polinomio.adiciona(poli)
    return polinomio

poli_1 = LerPoli("5x^3 + 4x^2 -3x^1 + 4")
poli_2 = LerPoli(("5x^3 + 1x^2 + 3x^1 + 5"))
poli_1.PrintPoli()
poli_2.PrintPoli()

   

poli_3 = SomaPoli(poli_1,poli_2)
poli_3.PrintPoli()
        

5x^3 + 4x^2 + -3x + 4
5x^3 + 1x^2 + 3x + 5
10x^3 + 5x^2 + 9


In [105]:
    i,j = 0
    while(i < len(poli_1_list)):
        if(poli_1_list[i][1] == poli_2_list[j][1]):
            poli_resultado.append([poli_1_list[i][0] + poli_2_list[j][0],poli_1_list[i][1]])
        

[1, 2, 3, 4]

AttributeError: 'list' object has no attribute 'PrintPoli'

In [12]:
class Poli:
    def __init__(self):
        self._head = None # Referencia ao primeiro elemento
        self._tamanho = 0 # Número de elementos
class noPoli:
    def __init__(self,)
    


1

4. Escreva um programa para encontrar todas as soluções para o problema das 8 rainhas. Observe que não basta apenas uma configuração viável, queremos descobrir todas elas. O programa deve ser capaz de continuar a busca após a primeira configuração válida.  Contar o número de soluções encontradas e imprimir essas configurações na tela.

In [200]:
tabuleiro = []
for i in range(8):
    for j in range(8):
        tabuleiro.append([i,j])
for i in range(8):
    for j in range(8):
        print(tabuleiro[8*i+j],end=' ')
    print()
print()


casas_livres = tabuleiro
rainhas = Stack()
solucoes = []
i,j = 0,0
while len(solucoes) < 5:     
    while len(casas_livres) > 0 and i < 8:
        while j < 8:
            if [i,j] in casas_livres:
                rainhas.push([i,j])
                casas_livres.remove([i,j])
                casas_livres = list(filter(lambda i_j:i_j[0] != i and i_j[1] != j, tabuleiro))
            j += 1
        j = 0
        i += 1

    if len(rainhas) == 8:
        print("Solução!")
        solucoes.append(rainhas)
        i = 0
        j = 1
        
    else:
        rainha_removida = rainhas.pop()
        
        i -= 1 
        j = 0 

    
    

[0, 0] [0, 1] [0, 2] [0, 3] [0, 4] [0, 5] [0, 6] [0, 7] 
[1, 0] [1, 1] [1, 2] [1, 3] [1, 4] [1, 5] [1, 6] [1, 7] 
[2, 0] [2, 1] [2, 2] [2, 3] [2, 4] [2, 5] [2, 6] [2, 7] 
[3, 0] [3, 1] [3, 2] [3, 3] [3, 4] [3, 5] [3, 6] [3, 7] 
[4, 0] [4, 1] [4, 2] [4, 3] [4, 4] [4, 5] [4, 6] [4, 7] 
[5, 0] [5, 1] [5, 2] [5, 3] [5, 4] [5, 5] [5, 6] [5, 7] 
[6, 0] [6, 1] [6, 2] [6, 3] [6, 4] [6, 5] [6, 6] [6, 7] 
[7, 0] [7, 1] [7, 2] [7, 3] [7, 4] [7, 5] [7, 6] [7, 7] 

Solução!
Solução!
Solução!
Solução!
Solução!


In [286]:
import numpy as np
tabuleiro = np.zeros([8,8])
print(tabuleiro)
def Livre(i,j):
    if tabuleiro[:,j].sum() > 0 or tabuleiro[i,:].sum() > 0:
        #print("linha ou coluna ocupada")
        return False
    else:
        i2 = i 
        j2 = j
        while i2 > -1 and j2 > -1:
            if tabuleiro[i2,j2] == 1:
                return False
            i2 -= 1 
            j2 -= 1 
        while i2 > -1 and j2 < 7:
            if tabuleiro[i2,j2] == 1:
                return False
            i2 -= 1 
            j2 += 1 
    return True
    




solucoes = []
tabuleiros = []
rainhas = Stack()
i,j = 0,0
gambi = 0 
while i < 8:
    gambi = 0 
    #print("mais um i",[i,j])
    while j <8:
        #print("será que é o j que endoidoi?",j)
        if Livre(i,j):
            #print("yey mais uma rainha :D, tamo com",rainhas.__len__())
            tabuleiro[i,j] = 1
            rainhas.push([i,j])
            i += 1
            j = 0  
            gambi = 1 
        else:
            j += 1
    if rainhas.__len__() == 8:
        print("Solução!")
        solucoes.append(rainhas)
        rainhas = Stack()
        print(tabuleiro)
        tabuleiros.append(tabuleiro)
        i = len(solucoes)//8
        j = len(solucoes)%8
        tabuleiro = np.zeros([8,8])
        gambi = 1
    elif gambi == 0:
        #print("é cumpadi, menos uma",[i,j])
        try:
            devolver = rainhas.pop()
            #print(devolver)
            i,j = devolver[0],devolver[1]
            tabuleiro[i,j] = 0
            j += 1
        except AssertionError:
            print("Assertion Error")

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Solução!
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]
Solução!
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]
Solução!
[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
Solução!
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1

In [294]:
x = 92
print(x//8, x%8)

11 4


In [296]:
from itertools import permutations

n = 8
cols = range(n)
for vec in permutations(cols):
    if (n == len(set(vec[i]+i for i in cols)) == len(set(vec[i]-i for i in cols))):
        print(vec)

(0, 4, 7, 5, 2, 6, 1, 3)
(0, 5, 7, 2, 6, 3, 1, 4)
(0, 6, 3, 5, 7, 1, 4, 2)
(0, 6, 4, 7, 1, 3, 5, 2)
(1, 3, 5, 7, 2, 0, 6, 4)
(1, 4, 6, 0, 2, 7, 5, 3)
(1, 4, 6, 3, 0, 7, 5, 2)
(1, 5, 0, 6, 3, 7, 2, 4)
(1, 5, 7, 2, 0, 3, 6, 4)
(1, 6, 2, 5, 7, 4, 0, 3)
(1, 6, 4, 7, 0, 3, 5, 2)
(1, 7, 5, 0, 2, 4, 6, 3)
(2, 0, 6, 4, 7, 1, 3, 5)
(2, 4, 1, 7, 0, 6, 3, 5)
(2, 4, 1, 7, 5, 3, 6, 0)
(2, 4, 6, 0, 3, 1, 7, 5)
(2, 4, 7, 3, 0, 6, 1, 5)
(2, 5, 1, 4, 7, 0, 6, 3)
(2, 5, 1, 6, 0, 3, 7, 4)
(2, 5, 1, 6, 4, 0, 7, 3)
(2, 5, 3, 0, 7, 4, 6, 1)
(2, 5, 3, 1, 7, 4, 6, 0)
(2, 5, 7, 0, 3, 6, 4, 1)
(2, 5, 7, 0, 4, 6, 1, 3)
(2, 5, 7, 1, 3, 0, 6, 4)
(2, 6, 1, 7, 4, 0, 3, 5)
(2, 6, 1, 7, 5, 3, 0, 4)
(2, 7, 3, 6, 0, 5, 1, 4)
(3, 0, 4, 7, 1, 6, 2, 5)
(3, 0, 4, 7, 5, 2, 6, 1)
(3, 1, 4, 7, 5, 0, 2, 6)
(3, 1, 6, 2, 5, 7, 0, 4)
(3, 1, 6, 2, 5, 7, 4, 0)
(3, 1, 6, 4, 0, 7, 5, 2)
(3, 1, 7, 4, 6, 0, 2, 5)
(3, 1, 7, 5, 0, 2, 4, 6)
(3, 5, 0, 4, 1, 7, 2, 6)
(3, 5, 7, 1, 6, 0, 2, 4)
(3, 5, 7, 2, 0, 6, 4, 1)
(3, 6, 0, 7, 4, 1, 5, 2)


In [217]:
tabuleiro = np.zeros([8,8])
tabuleiro[5,5] = 1
a = [5,5]
tabuleiro[a[0],a[1]] = 2
tabuleiro
tabuleiro[:,5].sum()

2.0

In [115]:
casas_livres = tabuleiro
rainhas = Stack()
solucoes = []
i,j = 0
while len(solucoes) < 92:  
    
    while len(casas_livres) > 0 or rainhas == 8:
        if [i,j] in casas_livres:
            rainhas.push([i,j])
            casas_livres.remove([i,j])
            casas_livres = list(filter(lambda i_j:i_j[0] != i and i_j[1] != j), tabuleiro)
        j += 1 
        
    if len(rainhas) == 8:
        print("Solução!")
        solucoes.append(rainhas)
        i = 0
        j = 1
        
    else:
        rainhas.pop()
        i -= 1 
        j = 0 

    
    

In [ ]:
#vou usar a lista python como pilha?

colunas_livres = [0,1,2,3,4,5,6,7,8]
rainhas = Stack()
resultados = []
while len(resultados) < 10:
    while i < 8:
        if colunas_livres == []:
            if rainhas.__len__() == 8:
                resultados.append()
                
            i -= 1
            rainha_removida = rainhas.pop()
            colunas_livres.append()
        else:
            rainha.push(colunas_livres[j])
            
        i+=1
            
            
